### PR TITLE
Grouped team section

### PR DESCRIPTION
**Pull request by Joshua-Nweze**
I created a group team section similar to the projects page

### CODE REVIEW

**Review by sayands — APPROVED** [review]
Looks good.

**Review by sayands — COMMENTED** [review]
I believe this is already addressed [here](https://github.com/CORD-ai/cord-website/pull/16)

**Review by AneeshBose — COMMENTED** [review]
On seeing the changes, adding some bottom padding for the headlines in each card and changing the font would make this the best PR for the team's page.

**Comment by Anindyadeep** [comment]
@Joshua-Nweze It looks nice, but make the changes according to what @AneeshBose mentioned. Also from my side, it would be better to make the cards a but smaller such that the dimension could be (No of cards x 5) ... So having 5 columns would result in lesser scrolling overall. Which would be cool in this case. 

Otherwise great Job @Joshua-Nweze.

**Comment by Joshua-Nweze** [comment]
Okay @AneeshBose I'll do that

**Pull request merged**
