### PR TITLE
UI testing

### PR DESCRIPTION
**Pull request by Abinash-Anand**
## This is the new design for the cord.ai website.
Here's a video representation

https://github.com/CORD-ai/cord-website/assets/74396889/004dee2a-f823-404e-95a3-a69d95e20662

> Video has been compressed through clideo.com

### CODE REVIEW

**Comment by Anindyadeep** [comment]
Make the icon better and transparent otherwise won't look good with that oval shape

**Review by Anindyadeep — COMMENTED** [review]
Looks good, some of the parts are very flashy, (might make it cliche), make it simple also change the icon (i.e. background must be transparent) and also make the components bit simpler. It should look like a research focused and asthetic in that sense.

**Comment by Abinash-Anand** [comment]
Thanks for the feedback. @Anindyadeep  I'll be making changes soon...
I had taken some insipiration from this website https://scale.com/ and a little bit from **openai** website.
**#AestheticGoals**

**Comment by Anindyadeep** [comment]
> Thanks for the feedback. @Anindyadeep I'll be making changes soon... I had taken some insipiration from this website https://scale.com/ and a little bit from **openai** website. **#AestheticGoals**

Awesome @Abinash-Anand , can't wait to see the new site.

**Comment by Ash-29** [comment]
@Abinash-Anand  There is a merge conflict , try to solve that

**Comment by Ash-29** [comment]
@Abinash-Anand Can you add that Neural Net background that we discussed earlier in next commit

**Comment by Abinash-Anand** [comment]
# Improvements
1. New Teams Section - 1. Research Advisors, 2.Mentors 3. Other Members
2. Blogs Section
3. Screening Task Section
4. New theme for the website-  (need a review on it) @Anindyadeep @Ash-29

**Comment by Anindyadeep** [comment]
@Abinash-Anand please remove the merge conflicts. Then I will review :)

**Comment by Anindyadeep** [comment]
> ## This is the new design for the cord.ai website.
> Here's a video representation
> 
>  cord.website.demo.mp4 
> > Video has been compressed through clideo.com

Hi, sorry for keeping this PR too long, let me know, we can sit in a call, and I can give you my feedbacks there. Thank you

**Comment by Abinash-Anand** [comment]
Hi Anindyadeep

I hope you're doing well

I wanted to reach out to inform you that I am available for a meeting
tomorrow evening after 6 PM.
Please let me know if this works for you.

Regards,
Abinash

**Pull request closed without merging**
