### PR TITLE
Updated navbar active link

### PR DESCRIPTION
**Pull request by Joshua-Nweze**
I updated the navbar active link class

### CODE REVIEW

**Comment by Anindyadeep** [comment]
Hey @Joshua-Nweze , have you created your own branch and pushing the code there or raising the PR directly to the main branch.

**Comment by AneeshBose** [comment]
> Hey @Joshua-Nweze , have you created your own branch and pushing the code there or raising the PR directly to the main branch.

He's created a PR from his to the main branch.

**Review by sayands — APPROVED** [review]
Looks good.

**Comment by Anindyadeep** [comment]
Why it's showing that it has 2 neutral checks? @sayands @AneeshBose

**Review by AneeshBose — APPROVED** [review]
LGTM.

**Comment by AneeshBose** [comment]
> Why it's showing that it has 2 neutral checks? @sayands @AneeshBose

Probably a netlify thing.

**Pull request merged**
