### PR TITLE
Remove Hackathon content

### PR DESCRIPTION
**Pull request by BalajiAI**
I've removed the Hackathon content from the website repo.

### CODE REVIEW

**Review by AneeshBose — CHANGES_REQUESTED** [review]
I think there is a `hackathon.html` page as well. Can we see if that needs to be removed as well? Thanks!

**Comment by BalajiAI** [comment]
> I think there is a `hackathon.html` page as well. Can we see if that needs to be removed as well? Thanks!

I've removed it too @AneeshBose. Along with images for hackathon which is in the assets/hackathon folder.

**Review by AneeshBose — APPROVED** [review]
LGTM!

**Comment by AneeshBose** [comment]
Merge as per convenience.

**Comment by BalajiAI** [comment]
> Merge as per convenience.

Maybe Let's wait for @Anindyadeep comments? If he said okay, then I'll merge.

**Comment by AneeshBose** [comment]
> Maybe Let's wait for @Anindyadeep comments? If he said okay, then we can merge.

Sure!

**Review by Anindyadeep — APPROVED** [review]
LGTM!

**Pull request merged**
