### PR TITLE
Teams page update

### PR DESCRIPTION
**Pull request by Ash-29**
Updates teams page and added community managers' details

### CODE REVIEW

**Comment by Ash-29** [comment]
@Nikunjbansal99 can you fix the dimensions issues with the managers photo

**Review by Anindyadeep — APPROVED** [review]
For now, everything seems fine. LGTM. But we might change some orderings of the community managers and fix the dimensions. 

Also one more thing, the community managers won't be included in the core team tabs. But yes that can be fixed by creation of other issues.

**Comment by Nikunjbansal99** [comment]
> @Nikunjbansal99 can you fix the dimensions issues with the managers photo

@Ash-29 yep, I will do that.

**Comment by BalajiAI** [comment]
Hey @Ash-29, for Atharva kulkarni there is an underscore between his first and last name. Same for Nikunj Pansari.

**Review by AneeshBose — COMMENTED** [review]
I see many names of managers who, from what I know, have done something worthwhile for CORD. Can you justify their additions @Ash-29 ? 

CC - @Nikunjbansal99 @Anindyadeep @BalajiAI Do you agree with the names? 
Imo, the website should only have folks who have worked hard for CORD.ai. Nobody else's name will go up.

**Comment by Nikunjbansal99** [comment]
I agree with Aneesh

**Comment by Ash-29** [comment]
> For now, everything seems fine. LGTM. But we might change some orderings of the community managers and fix the dimensions.
> 
> Also one more thing, the community managers won't be included in the core team tabs. But yes that can be fixed by creation of other issues.

Yes they will not be included in core teams tab , but can be added in "teams" page . Later we can change their location

**Comment by Anindyadeep** [comment]
I also strongly agree with @AneeshBose. Contribution should really matter. This would not be fair for the folks who have worked hard with their contributions. Coz in the both the case the names are listed.

**Comment by BalajiAI** [comment]
Yes, @AneeshBose and @Anindyadeep. I also feel the same. Some of the people didn't contribute anything to CORD, and some of them contributed only at the beginning of CORD, didn't hear from them afterwards.
@Ash-29 knows very well, who have contributed and who doesn't.

**Comment by Nikunjbansal99** [comment]
@Ash-29 Any update? At least provide the contributors' names to me. So I can resolve this conflict today as we are Going Live Tomorrow.

**Comment by Ash-29** [comment]
Are we going live tomorrow, who decided ??? at least anyone can inform other people like us in the core group that we are going live tomorrow... strange

As far as I know, people who really did hard work are now core members, we have 9 community managers and out of them, 6 are doing their duties.
1. Annanya Mishra
2. Atharva Kulkarni
3. Ankit Gupta
4. Nikunj Pansari
5. Jaskaran Singh Chhabra
6. Sanya Sinha

I think these profiles should be added to the website, now for the rest profiles, I'll try to conduct a meeting probably in the next week to review their work as we did in the core team. For now, I'm, removing some profiles, those who are not in the managers' group maybe they don't know what's going on in the group but disappointed to see people who are the part of the community managers' group for a long time, they are saying nothing is going on in that group.

**Pull request closed without merging**
